### ISSUE TITLE
move templates out of repo

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#146]
create a `popper-default-experiments` github repo and move `templates` to it.

**Comment by namnatulco** [comment]
this commit broke a whole bunch of links on the website... and I can't find your templates repository anywhere :)

**Comment by ivotron** [comment]
Hi @namnatulco , sorry for the confusion! We just updated the site to reflect this change. There shouldn't be any broken links anymore (on <http://falsifiable.us> nor [readthedocs](http://popper.readthedocs.io)).

Regarding the `templates/` folder, we now have a list of popperized repos at [this github organization](https://github.com/popperized). The list of pipelines that were in the `templates/` folder are in [this repo](https://github.com/popperized/popper-readthedocs-examples).

Due to the change in 2e0d70cffddbb18fc53844c05fd90aa386ebc40a, we removed the `add`, `info` and `list` subcommands from the CLI. We have in our backlog a list of issues (specifically #70, #144 and #145) that will bring back the ability to search and import existing pipelines.

Also, we have a preliminary version of a [Popper lesson](https://ivotron.github.io/popper-lesson/) written in the [software carpentry](https://software-carpentry.org/lessons/) format that you might find useful.

Please let us know if you have any other question.

**Comment by namnatulco** [comment]
Thanks!

I was mainly looking for any repository that doesn't use docker (ideally slurm), since the cluster I'm using isn't administrated by our institute, which is why I was looking for the templates (I thought [this](https://github.com/popperized/popper-readthedocs-examples/tree/master/pipelines/blis) would be what I'm looking for, but not quite).

Anyway,  I'm hoping to port the scripts I'm currently using to something that's popper-compliant after the deadline; if you're interested I'd be happy to contribute the repository as an example.

**Comment by ivotron** [comment]
> that doesn't use docker (ideally slurm)

Oh, I see. In that case, [this pipeline](https://github.com/popperized/popper-readthedocs-examples/tree/master/pipelines/mpip) might be more relevant. It's a bit rough, but I've tested it on an HPC center that uses SLURM. This runs from your machine (so no need to install popper on a supercomputer node), connects to a login node and submits a job.

> if you're interested I'd be happy to contribute the repository as an example.

Yes, please! Let us know if we can help in any way.
