### ISSUE TITLE
cli: add support for running a workflow in vagrant

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#172]
Add vagrant as a runtime available for running workflows. We can have a box with Docker inside to which we share the workspace.

**Comment by JayjeetAtGithub** [comment]
@ivotron [`this`](https://pypi.org/project/python-vagrant/) package is a python api wrapper for `vagrant-cli`, but the problem is that it is not being maintained for 2 years now and also lacks proper documentation. Please have a look. Is there any alternative vagrant-cli wrapper? If this package is really unusable then we might have to proceed by using `utils.exec_cmd` to process raw commands. What do you say ? Thanks :smile:

**Comment by JayjeetAtGithub** [comment]
@ivotron Also what are providers that will be used with `VagrantRunner` in our case, like from VirtualBox, docker, VMWare, etc?

**Comment by JayjeetAtGithub** [comment]
@ivotron If we would use raw commands, then how to get back the output in `utils.exec_cmd()` as a byte string?

**Comment by ivotron** [comment]
thanks a lot for looking into this @JayjeetAtGithub! it seems that there's quite a significant amount of effort put into the [`python-vagrant`](https://github.com/todddeluca/python-vagrant) project. I'd vote for using that

**Comment by JayjeetAtGithub** [comment]
@ivotron Sure ! Thanks

**Comment by JayjeetAtGithub** [comment]
@ivotron Can we use a `vagrant://` prefix with box names to refer boxes from [here](https://app.vagrantup.com/) in the `uses` attribute of an action?

**Comment by ivotron** [comment]
yeah, that's a great idea!
