### ISSUE TITLE
Question about using popper for applications that take large quantities of computer time

### ISSUE THREAD

**Issue by kbarnhart** [systemslab/popper#308]
Hi Popper!

I'm an earth scientist and numerical modeler who does a lot of numerical experiments. I'm very interested in using modern tools for making my research more reproducible and was thus very excited to find out that popper existed.

In general I script all of the numerical experiment creation, job submission, post-processing analysis, and visualization steps in my work. I also typically use only open source software.

My work, however, often uses a large amount of compute time (e.g. many thousands of SU) and is run on a HPC platform. Post-processing steps and visualization also are time intensive (e.g. a day of run time on 1 or 2 - 24 core nodes). 

As I've come to understand the Popper workflow based on the documentation, a key part of popper's use is by re-running and validating the results (through the `popper run my_pipeline_name` command).

Can you provide any guidance or recommendations for using popper in a context in which it is not computationally feasible to have the entire workflow re-run. Perhaps this information is hidden somewhere in the documentation, in which I'm sorry I wasn't able to find it. 

thank you!

**Comment by ivotron** [comment]
Hi! Thanks a lot for reaching out. First of all, the fact that you have everything scripted is a huge step. 

> Perhaps this information is hidden somewhere in the documentation, in which I'm sorry I wasn't able to find it.

This is not documented anywhere 😞But this question was asked recently on our [gitter channel](https://gitter.im/falsifiable-us/popper) and this is what we answered:

-----

The `popper run` command has a `--skip` argument that can be used to execute a pipeline in multiple steps. So for example, assuming we have a pipeline with the following scripts: `setup`, `run`, `post-run` and `validate`. Then, you could run:

```bash
popper run --skip post-run,validate
```

which would run the first part (setup and execution). Then, later you either manually check whether your jobs are done or you automate it in the `post-run` script (I know SLURM has a way of querying the status of your jobs) and run:

```bash
popper run --skip setup.sh,run.sh
```

and the above will just execute the second half of your pipeline. The `post-run` script could either first check the status of your jobs, or just assume that they’re done and will `scp` the data to your local machine (or move output to a NAS, etc.), and the `validate` will invoke the analysis.

Would something like this work in your case?

-----

Another practice we have been following is to have a specific set of parameters for the pipeline with the goal of running a smaller scale simulation/analysis. The idea is to use this when running on a CI service such as [Travis](https://travis-ci.org) in order to test the entire pipeline in a relatively short amount of time (Travis times out jobs after 3 hours). So this ends up looking something like [this](https://github.com/ivotron/quiho-popper/blob/master/pipelines/single-node/setup.sh), i.e. a conditional in a stage that, depending on the environment (in this case a `CI` variable defined), the parametrization and setup is different, but the rest of the pipeline runs in the same fashion. While this approach doesn't really executes the actual original simulation, at least it lets us test the integrity of the scripts.

We hope that helps!

**Comment by kbarnhart** [comment]
@ivotron thanks for all the answers, both approaches you bring up (`--skip` and running a pipeline at smaller scale) will probably be useful in my work. I'm glad to know about both and will let you know if/when I come up with a problem that I can't solve with either. 

Thanks again for developing popper!
