### ISSUE TITLE
Add runtime to Docker env

### ISSUE THREAD

**Issue by pseeth** [systemslab/popper#454]
When running pipelines inside Docker environments, it'd be helpful to be able to add a runtime argument to popper (e.g. --runtime=nvidia). This would be helpful for using containers with GPU access (nvidia-docker runtime). By default, the runtime for Docker is [runc](https://github.com/NVIDIA/nvidia-docker/wiki/Advanced-topics). So if unspecified, the popper run could be:

    docker run --rm --runtime=runc [command]

And that would be the same as the current behavior. If a runtime is specified (ideally in .popper.yml file), it could change to:

    docker run --rm --runtime=nvidia -ti [command]

It'd be neat to be able to specify runtimes in order of preference. That way if one of the runtimes doesn't exist (nvidia, to use GPU) on the machine trying to reproduce results, then the next runtime will be used (runc, to use CPU). 

    pipelines:
      train-model:
        envs:
        - train_env
        runtimes: nvidia,runc
        path: pipelines/train-model
        stages:
        - train
        - test

Something like that, maybe. If only nvidia was listed under runtimes, the run could fail with an informative error (job must be run on GPU).

As an aside - the current timeout for running popper pipelines is low for machine learning where training a model can take days. Is there a way to eliminate the timeout argument or should I just make it incredibly long? If so, is there a way to specify the timeout value in .popper.yml?

Thanks for your time! I've really been enjoying using Popper.

**Comment by eltrufas** [comment]
Hello,

First of all, thanks for opening this issue and I'm glad you're enjoying using Popper so far!

I really like this idea. Maybe instead of adding an option specifically for selecting runtimes to `.popper.yml`, we could allow specifying a list of parameters that should be passed over to `docker run`. This would allow for setting the runtime but it'd also cover other cases, such as mounting volumes and such. We could also allow multiple sets of parameters for fallbacks. So something like:

```yml
pipelines:
  train-model:
    envs:
      train_env:
        args:
        -  --runtime=nvidia
        -  --runtime=runc
    path: pipelines/train-model
    stages:
    - train
    - test
```

In the meantime, as a workaround, I think you can set the default runtime to `nvidia` your `/etc/docker/daemon.json` to be able to use a different runtime with docker.

As for the timeout, currently your best bet is setting it to a very high value. I also opened [another issue](https://github.com/systemslab/popper/issues/455) for this.

**Comment by pseeth** [comment]
Yes that'd be great. Generalizing it to multiple arguments for the environment would be excellent (another popular one is --ipc=host when training models in a Docker environment in PyTorch with parallel processes for data loading).
