### ISSUE TITLE
Cannot install popper entirely in the user home directory

### ISSUE THREAD

**Issue by dsfalves** [systemslab/popper#468]
When installing popper through 'pip install --user popper' I noticed that popper fails to install because it doesn't have access to install the bash completion file `bash-completion.sh`.
I am running Archlinux with the following as the output for `uname -rv`: `4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018`
Python version is `Python 3.7.0`
Pip version is `pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)`
Permissions for `/usr/local` are `drwxr-xr-x 11 root root 4.0K Mar 26  2017 /usr/local`

It seems that the problem is that I do not have write access to `/usr/local`, where `bash-completion.sh` would be installed. I could modify my computer to allow to write there, however I intend to use popper on computers in which I would not be able to do so, but I am otherwise able to install python libraries locally using `pip install --user`.

**Comment by ivotron** [comment]
hey @dsfalves , thanks a lot for reporting this. We just released version 1.1.1 and it's now available via `pip`. This should fix the issue you're having since we are not touching `/usr/local` anymore (I thought we were already not doing that). Bash completion is enabled by manually copying the file as indicated [here](https://github.com/systemslab/popper/tree/master/cli#bash-completion). Thanks!
