### ISSUE TITLE
cli: popper takes a really long time to move from stage to stage in a pipeline

### ISSUE THREAD

**Issue by pseeth** [systemslab/popper#480]
Hi, I'm not sure if I'm doing something wrong nor do I know how to reproduce, but popper takes a very long time (like 10 minutes) to transition from stage to stage. I'm not sure what's going on...has anyone else had a similar problem? If not, I can keep troubleshooting on my own. Again, sorry for not having specifics but this happens across a bunch of popperized projects that I have.

Thanks,

Prem

**Comment by ivotron** [comment]
hey @pseeth , thanks for reporting this. Can you please point to the pipeline you are running, so that I can try to reproduce the behavior. And also, can you please specify how are you installing popper and which version you're using?

**Comment by qwofford** [comment]
This is an issue for me in one of my pipelines. I'll investigate further when possible, but for now I can say that whatever is taking time happens before the setup stage begins generating logs, and it's not obvious what the hold-up is when monitoring htop

**Comment by qwofford** [comment]
I think it would be nice to include some logging in the "popper" directory for whatever is happening before and in-between stages (and after). I think the issue here is that we don't have a way to reason about the things popper is doing with a pipeline in the background. Verbose mode could be useful for this occasional use case.

**Comment by qwofford** [comment]
Something in here I guess

https://github.com/systemslab/popper/blob/e8aaf3bf73805efb6e28466d86fbf0a9dda5f4e9/cli/popper/commands/cmd_run.py#L113-L129

**Comment by ivotron** [comment]
@qwofford @pseeth I'm having difficulties trying to reproduce this. I have create a new issue (#498) that will track the addition of logging capabilities so that users can get a better idea of what Popper is doing. That will be part of the next version of Popper, so once that's available, hopefully you can test again your end to see if this is still the case.
