### ISSUE TITLE
doc: pip install command in CLI Doc results in the wrong version

### ISSUE THREAD

**Issue by akashrajr1** [systemslab/popper#522]
For the CLI Doc [here](https://github.com/systemslab/popper/blob/master/cli/README.md),  `pip install popper` / `pip3 install popper` both install the wrong version of popper i.e. version 1.2.2
![pip3_wrong_version](https://user-images.githubusercontent.com/21059924/53843336-0ae06d00-3fc8-11e9-8fee-3d92d387fd78.JPG)

**Comment by ivotron** [comment]
hey @akashrajr1 , thanks a lot for pointing this out. We are working towards version 2.0. Since we haven't released it yet, we haven't published anything on pypi yet. As part of project [#12](https://github.com/systemslab/popper/projects/12), we have a couple of issues related to upgrading the documentation. In particular, #507.

I'll close this as a duplicate of #507.
