### ISSUE TITLE
cli: interactively define secrets

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#566]
If a workflow defines secrets, and they are not available in the environment, prompt the user for their values. This needs to take care of the case when `popper run` is executed by a CI service, in which case the prompt is skipped

**Comment by akashrajr1** [comment]
Hi @ivotron, I was actually thinking about this issue for my proposal.
While writing for tests, I had to manually lookup and define secrets for the workflow, so I was thinking of some way to automate that. 
We can have two modes of operation to populate secrets:
1. Interactive method - This being the default method
2. Dummy populate - We can add `--dummy-secrets` option, which would automatically define secrets (This part of the feature being useful only for developers)

Also besides interactive mode, we can include an option `--secrets-config` to specify a config file for the user. So that once the user becomes aware of what secrets need to included, he can include them in a config file and reduce  the labor of redefining them each them. 
We can also generate the secrets file for the user, after the first mode of operation: `interactive`, so that it might be coupled with `--secrets-config` later on

**Comment by akashrajr1** [comment]
PS: @ivotron as I actually wanted to include this in my proposal, should I start on this PR, before the proposal phase or after it? 
Thanks!

**Comment by JayjeetAtGithub** [comment]
@ivotron I thought of solving this issue in a different way before. Would you like to know my approach ? This will not require adding extra flags to `popper run`. Thanks !

**Comment by ivotron** [comment]
hey @JayjeetAtGithub, could you comment your idea here? Maybe we can discuss it and @arshul can incorporate it to #573. Doing this transparently (i.e. without needing a flag) would be friendlier to the user.

**Comment by JayjeetAtGithub** [comment]
@ivotron Travis CI sets an env variable `CI=true` by default for all builds. We can check if this var is set to `'true'` in the `check_secrets()` function. If not set or set to `'false'` we can prompt the user to enter user the values. To make this feature generic for all CI services like [`travis`](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables), [`circleci`](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-job) what we can do is that we can define a custom env var `IS_CI=True/False` in the CI config file and check for this var through code.

**Comment by arshul** [comment]
> Doing this transparently (i.e. without needing a flag) would be friendlier to the user.

In the current implementation, You need the flag only in the case of TravisCI. By default, the prompt appears when executing `popper run`, so the user does not need to do anything extra, if a secret is not defined, the user will get the prompt to enter the value, the flag is only passed in the Travis' script so that it does not stop for the prompt in the test scripts.

Also, @JayjeetAtGithub's way can be implemented, but it will require us to go to Travis or any other CI's GUI to enter the variable, but flag can be added to script more conveniently in my opinion.

@ivotron you can tell me which way to proceed and I will do the required changes.

**Comment by JayjeetAtGithub** [comment]
Hi @arshul Environment variables can be defined in the CI's config files itself. You may refer to [this](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables). Thanks :+1:
