### ISSUE TITLE
cli: use click-log

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#586]
make use of https://github.com/click-contrib/click-log to improve treatment of debug, verbose, quiet modes.

**Comment by akashrajr1** [comment]
@ivotron I wanted some clarification about this issue.
1. Do we need to also change the implementation of `info` and `fail` in `utils` to use `click_log`? With `setLevel` we can filter out the level of logs we want.  `fail` being equivalent to `ERROR` level, `debug` equal to `DEBUG`. No changes for `quiet`. So without changing `fail` we won't be able to exercise the full power of `click_log`
2. And is `info` equivalent to `INFO` logging level? Shouldn't `info` be always printed out to the stdout irrespective of the level set by `setLevel`?
3. Are we condensing the functionality of `--debug` into the inbuilt `--verbosity` option. Because in the click log [docs](https://click-log.readthedocs.io/en/stable/), `--debug` is implemented as a `setLevel`
> The simple_verbosity_option() decorator adds a --verbosity option that takes a (case-insensitive) value of DEBUG, INFO, WARNING, ERROR, or CRITICAL, and calls setLevel on the given logger accordingly.

**Comment by ivotron** [comment]
thanks a lot for working on this @akashrajr1 ! please see my answers inline


> 1. Do we need to also change the implementation of `info` and `fail` in `utils` to use `click_log`? With `setLevel` we can filter out the level of logs we want.  `fail` being equivalent to `ERROR` level, `debug` equal to `DEBUG`. No changes for `quiet`. So without changing `fail` we won't be able to exercise the full power of `click_log`

yes, that would be ideal. There might also be a way of disabling/re-enabling logging, in which case click-log would also work for implementing the `--quiet` functionality

> 2. And is `info` equivalent to `INFO` logging level? Shouldn't `info` be always printed out to the stdout irrespective of the level set by `setLevel`?

yes, it is equivalent. In our case, `info` is the default logging level

> 3. Are we condensing the functionality of `--debug` into the inbuilt `--verbosity` option. Because in the click log [docs](https://click-log.readthedocs.io/en/stable/), `--debug` is implemented as a `setLevel`

not sure I understand this question. do you mean allowing users to specify a `--verbosity` option? In our case, popper users will not be aware of logging levels. Instead, the semantics we have is: actions are verbose by default and they're silenced when `--quiet` is given. If `--debug` is given, then we print everything that popper is doing.

**Comment by akashrajr1** [comment]
What I meant was that according to the [docs](https://click-log.readthedocs.io/en/stable/) for click_log, the `--debug` option is to be accessed instead by using `--verbosity DEBUG` (`--verbosity` added by the `simple_verbosity_option()` decorator). So are removing `--debug` in favor of `--verbosity DEBUG`?
If we are not removing `--debug`, wouldn't it be better to just use the `logging` module instead?

**Comment by ivotron** [comment]
I see. Besides the decorator, the library also adds a prefix to messages and colorizes them according to their level. If you feel that it would be better to use `logging` and do the prefixing/colorizing on our end, then yeah, we could not use `click-log` and just use `logging`. Up to you.

**Comment by akashrajr1** [comment]
Yeah, I think doing prefixing/colorizing on our end would be better as it would allow the retention of the current format of messages. `click-log` colorizes the only prefix, not the entire message as it is currently being done
