### ISSUE TITLE
cli: skip unreachable actions

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#611]
An action is unreachable if no other action is referencing it in a `needs` attribute or in the `resolves` attribute of a `workflow` block. When `popper run` executes, we can show a `WARNING` message letting users know about unreachable actions (list their names). In addition, unreachable actions are currently being executed when they shouldn't

**Comment by akashrajr1** [comment]
Two approaches that come to my mind
* We can precompute which actions are reachable and use it to check during execution whether an action should be executed.
* Over [here](https://github.com/systemslab/popper/blob/634c14ca3a47c9df0c2b4d3e71649681ba9325f1/cli/popper/gha.py#L93-L96) in `normalize()` instead of simply copying our workflow actions, we can change it so that we do a traversal instead and store that traversed result. We can thus be sure that unreachable actions are not copied over in `self.wf` and thus not executed. If we want to show `WARNING` message for unreachable actions, we can compare actions in new and old graphs and find the unreachable actions

The first one leads to extra iterations when they are not necessary, but the second one loses information about the graph in form of removing unreachable actions ( though we can also save that information separately) 

I would like to hear your thoughts @ivotron on this

**Comment by ivotron** [comment]
thanks for proposing those alternatives @akashrajr1! The main issue here is that in [`Workflow.complete_graph()`](https://github.com/systemslab/popper/blob/634c14ca3a47c9df0c2b4d3e71649681ba9325f1/cli/popper/gha.py#L158-L159), we currently assume that any action without a `needs` attribute is at the root of the workflow. This assumption is wrong, since an action without `needs` might not be reachable  from the Workflow's `resolves`. In other words, the conditions for an action to be a root action are that (1) it does not have a `needs` attribute and (2) it is reachable from the `resolves` attribute of a `workflow` block.

Thus, in this same `Workflow.complete_graph()` method, we can create a list of all actions for which only (1) is true and, at the end of the method, we show a WARNING message listing their names. Since these won't be part of the `wf['root']` list, they won't be executed by `popper run`.
