### ISSUE TITLE
README.md first sentence is wrong

### ISSUE THREAD

**Issue by gflofst** [systemslab/popper#679]
"Popper is a Github Actions (GHA) workflow execution engine"

While I understand the intent, this isn't correct. You have always been adamant that this is not a set of tools, but an approach to using tools. How about something like this:

"This expression of the Popper Convention (https://falsifiable.us) is implemented using the GitHub Actions (GHA) workflow engine"

**Comment by carlosmalt** [comment]
I think workflow specification is more central to Popper than other tools. At some level you have to specify your workflow no matter what tools you are using. Popper has always been about trying to standardize that specification, to the point that people were criticizing Popper of being just another workflow engine. So the first sentence is basically saying, Popper is not reinventing workflow specification. Instead it is adopting the language put forth by GHA and supporting all the features that come with it.

**Comment by gflofst** [comment]
My issue with it was that the way that it was stated, it reads as if Popper is solely ONLY GHA and not possible to be anything else. I was recommending generalizing the language a bit. The "use the tools you know as love" aspect I think is one of the contributions.

**Comment by ivotron** [comment]
I agree with what @carlosmalt wrote. @gflofst, see [this post](https://medium.com/getpopper/announcing-popper-2-0-a-github-actions-executioner-in-python-cf25620c021e) for more on the rationale behind using GHA as the basis for Popper workflows. In short: in the Popper v1.x series, we were using a (formally unspecified) workflow format; we wanted to move forward and "do it right". Instead of coming up with yet another workflow language, we decided to take one that (1) is lightweight, (2) its spec is open, and (3) is flexible enough so it can be used in multiple domains.

>  The "use the tools you know as love" aspect I think is one of the contributions.

This is still valid. I cannot think of a tool that one would not be able to wrap in a Popper workflow. In scenarios where Docker cannot be installed, Popper supports Singularity or running directly on the host (see [here](https://popper.readthedocs.io/en/v2.1.0/sections/extensions.html)).

**Comment by ivotron** [comment]
@gflofst another way to put it would be that prior to v2.x, the "popper convention" was something that was fuzzily specified. Now we have a formal spec, which has the consequence of turning Popper into a workflow engine.

**Comment by gflofst** [comment]
I withdraw my comment then. :-) I was out of the loop that this change had occurred. I think this is a good thing since I know Microsoft will make the GHA pieces available in other contexts eventually. Nadella understands that open source and cloud are how to dominate the 21st century and making the best open tools and making them trivial to use is how you win.
