### ISSUE TITLE
cli: allow flags in commit message-driven execution

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#696]
currently, the keyword that allows to specify what workflows to run (in a commit message) has the form:

```
popper:whitelist[...]
```

Now that there are multiple ways in which we can control the execution of a workflow, we can generalize this so that we can take all the same flags that can be given to `popper run`. For example:

```
popper:run[--on-failure cleanup --wfile path/to/main.workflow]
```

we can take more than one of this.

**Comment by ivotron** [comment]
we can also take this opportunity to deprecate the `--wfile` flag, and instead take it as an argument, something like:

```
popper run <options> [action|wfile]
```

**Comment by JayjeetAtGithub** [comment]
```
popper:[--on-failure cleanup --wfile path/to/main.workflow]
```
Does this arrangement apply to only those options which take a workflow/action as value ?

**Comment by ivotron** [comment]
the idea is to allow passing any flag that can be passed to the `popper run` command. We could instantiate another click context by calling the [`make_context()`](https://click.palletsprojects.com/en/7.x/api/?highlight=parse#click.BaseCommand.make_context) method of the `cmd_run` command, so that we don't need to parse this ourselves

**Comment by JayjeetAtGithub** [comment]
@ivotron Now that we deprecated the `popper:whitelist` and `popper:skip`, so if an user want to whitelist 1 workflow he would ideally pass it as an argument to `popper run` by doing `popper run /path/to/workflow`. But if they want to whitelist more than 1 workflow, what should they do ?  For this case, we can allow `skip` to take workflow inputs as well, so that the workflows not required can be skipped. What do you think ?

**Comment by ivotron** [comment]
yeah, that's a good idea
