### ISSUE TITLE
cli: singularity not using image cache

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#716]
to reproduce:

```hcl
workflow "foo" {
  resolves = "b"
}

action "a" {
  uses = "actions/bin/cli@master"
  args = ["ls -la"]
}

action "b" {
  needs = "a"
  uses = "actions/bin/cli@master"
  args = ["ls -la"]
}
```

singularity builds the container image from scratch for both `a` and `b`, as opposed to reusing the cache for `b`.

**Comment by JayjeetAtGithub** [comment]
@ivotron I was trying out to reproduce this when I found that after building the container for the first time, it uses cached blobs from the next time. Please refer to [this](https://travis-ci.com/JayjeetAtGithub/popper-sample-project/builds/121795098) link. Here it seems like, for the first time, 25.84 Mb of data was pulled, but for the second time it was skipped because of caching.

Did I catch the issue correctly? Thanks
