### ISSUE TITLE
cli: support for custom arguments flag(--arg) in popper run

### ISSUE THREAD

**Issue by realsdx** [systemslab/popper#753]
Currently `popper run` command doesn't support custom arguments. Custom arguments cloud be really helpful for this type of use case :

```hcl
action "run" {
  uses = "docker://paddlepaddle/paddle:$_TAG"
  args = ["-some", "-args", "-for", "-paddle"]
}
```

and popper could be invoked like this:

```bash
popper run --arg _TAG=1.6.2
```

**Comment by vipulchhabra99** [comment]
@ivotron I would like to work on this but will require your guidance to add this new feature.

**Comment by ivotron** [comment]
thanks a lot for volunteering to work on this @vipulchhabra99 , please go ahead. The idea is to provide functionality to [Google Cloud Build's substitutions feature](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions). In terms of implementation, this can be done by applying a post-parsing step that substitutes all the argument references for their values. Since this would be done _before_ the workflow gets executed, the workflow execution code shouldn't be affected by this.
