### ISSUE TITLE
Make interactive artifacts likes Jupyter notebooks behave the same

### ISSUE THREAD

**Issue by carlosmalt** [systemslab/popper#791]
I've been trying to share a jupyter notebook that is used in a Popper workflow with a student via git. Interactively running the Jupyter notebook _outside_ a workflow for debugging or teaching purposes requires the same, say, python environment for the notebook's kernel -- otherwise the notebook is less likely to work for the other one.

I think this is related to the whole debugging popper issue: is it possible to start a workflow action that creates an interactive session like a `jupyter notebook` process, thereby creating an easy way to leverage the workflow's environment? Quitting the interactive session will then complete the action. It's not reproducible in the sense of the result, but it's reproducible in the sense of the interactive artifact's behavior.

**Comment by ivotron** [comment]
@carlosmalt I think the way to go about this (and for any complex software package in general) is to make use of docker images that are built externally rather than installing software as part of the workflow. For jupyter in particular, there is the [docker-stacks](https://github.com/jupyter/docker-stacks) project, as well as the images from the [tensorflow](https://hub.docker.com/r/tensorflow/tensorflow/) project. These are tested/updated continuously. 

These images also allow you to make use of them interactively, by running something like:

```bash
$ docker run -it --rm -v $(realpath ~/notebooks):/tf/notebooks -p 8888:8888 tensorflow/tensorflow:latest-jupyter
```

and then opening a browser and pointing it to `localhost:8888`. All this is documented in the tensorflow docker hub README by the way.

In addition to the above, a workflow that makes use of the same image but in non-interactive mode by invoking `nbconvert`, as shown [here](https://github.com/popperized/popper-examples/blob/master/workflows/pgbench/main.workflow#L14). So using these pre-built images means that whether you're interactively looking at a notebook or running it in a workflow, you'd always be using the same version of jupyter and associated dependencies. Note that you can also extend the images so that other python packages can be added

**Comment by ivotron** [comment]
closing this for now. please re-open this issue if the above does not solve the issue.
